export type {
  ArchitectureDecision,
  ArchitectureRule,
  AwsRegion,
  BudgetCheckResult,
  CodeAnalysis,
  CostBreakdown,
  CostLineItem,
  DbCriticality,
  DbEngine,
  EC2Config,
  EvaluationResult,
  InstanceArch,
  InstancePrice,
  ProjectComplexity,
  RDSConfig,
  RegionPriceTable,
  RuleAction,
  RuleCondition,
  StoragePrice,
  TrafficScale,
  UserInput,
  VpcConfig,
  VpcType,
} from './rule-types.js';

export {
  AP_NORTHEAST_2_PRICES,
  ARCHITECTURE_RULES,
  PRICE_TABLES,
  calculateMonthlyCost,
  checkBudget,
  evaluateRules,
} from './architecture-rules.js';
